#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hoe-debugging
Version  : 1.2.1
Release  : 7
URL      : https://rubygems.org/downloads/hoe-debugging-1.2.1.gem
Source0  : https://rubygems.org/downloads/hoe-debugging-1.2.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-hoe-git
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= hoe-debugging
* http://github.com/jbarnette/hoe-debugging
== Description
A Hoe plugin to help you debug your C extensions. This plugin provides
<tt>test:gdb</tt> and <tt>test:valgrind</tt> tasks (plus a few
variants).

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hoe-debugging-1.2.1
gem spec %{SOURCE0} -l --ruby > rubygem-hoe-debugging.gemspec

%build
gem build rubygem-hoe-debugging.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hoe-debugging-1.2.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/hoe-debugging-1.2.1
rake --trace test TESTOPTS="-v"
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/hoe-debugging-1.2.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/ValgrindHelper/cdesc-ValgrindHelper.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/ValgrindHelper/directory-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/ValgrindHelper/ensure_directory_exists-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/ValgrindHelper/formatted_ruby_version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/ValgrindHelper/matching_suppression_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/ValgrindHelper/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/ValgrindHelper/parse_suppressions_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/ValgrindHelper/project_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/ValgrindHelper/save_suppressions_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/ValgrindHelper/valgrind-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/ValgrindHelper/version_matches-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/cdesc-Debugging.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/gdb_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/hoe_debugging_check_for_suppression_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/hoe_debugging_command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/hoe_debugging_make_test_cmd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/hoe_debugging_ruby-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/hoe_debugging_run_valgrind-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/hoe_debugging_valgrind_helper-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/Debugging/valgrind_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/Hoe/cdesc-Hoe.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/page-CHANGELOG_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-debugging-1.2.1/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/hoe-debugging-1.2.1/CHANGELOG.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/hoe-debugging-1.2.1/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/hoe-debugging-1.2.1/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/hoe-debugging-1.2.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/hoe-debugging-1.2.1/lib/hoe/debugging.rb
/usr/lib64/ruby/gems/2.2.0/specifications/hoe-debugging-1.2.1.gemspec
